// TODO Implement this library.
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnJxxvC39OtoZcax_WsuCPbC4KjzFyVPw',
    appId: '1:895692739688:web:c5c09f71ce79c108e8d7dd',
    messagingSenderId: '895692739688',
    projectId: 'mobilprog-7a60d',
    authDomain: 'mobilprog-7a60d.firebaseapp.com',
    storageBucket: 'mobilprog-7a60d.appspot.com',
    measurementId: 'G-7KY664608L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh0tP6HT7qOWA1-CMMgwo_YnNmO5j2WMQ',
    appId: '1:895692739688:android:e52928bfc37cf568e8d7dd',
    messagingSenderId: '895692739688',
    projectId: 'mobilprog-7a60d',
    storageBucket: 'mobilprog-7a60d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9_QfreRLuVJ1kDAxltd3-6n5bD43pkSM',
    appId: '1:895692739688:ios:20c57cd0b66ac488e8d7dd',
    messagingSenderId: '895692739688',
    projectId: 'mobilprog-7a60d',
    storageBucket: 'mobilprog-7a60d.appspot.com',
    iosBundleId: 'com.example.mobilprogramlamauyg',
  );
}
