// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANrhxOZDn7Pb6KWL-dOrOIAP4Syqn9V1s',
    appId: '1:890687616159:web:ad53d54307b4d228115eaa',
    messagingSenderId: '890687616159',
    projectId: 'mobilprogramlamauyg',
    authDomain: 'mobilprogramlamauyg.firebaseapp.com',
    storageBucket: 'mobilprogramlamauyg.appspot.com',
    measurementId: 'G-FPD80EYQKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZmr6SZI_J_fs3np2veWk1E-sBNBUjObQ',
    appId: '1:890687616159:android:abbe5e88e2b748d5115eaa',
    messagingSenderId: '890687616159',
    projectId: 'mobilprogramlamauyg',
    storageBucket: 'mobilprogramlamauyg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqQcBZl8knJIFPQpFKH7r-LrGUf1Alwe0',
    appId: '1:890687616159:ios:9be2b8a7d59d57aa115eaa',
    messagingSenderId: '890687616159',
    projectId: 'mobilprogramlamauyg',
    storageBucket: 'mobilprogramlamauyg.appspot.com',
    iosClientId: '890687616159-eqb0nsskb9lhs5nk13o1gpjmq5s0h7vu.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobilprogramlamauyg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqQcBZl8knJIFPQpFKH7r-LrGUf1Alwe0',
    appId: '1:890687616159:ios:9be2b8a7d59d57aa115eaa',
    messagingSenderId: '890687616159',
    projectId: 'mobilprogramlamauyg',
    storageBucket: 'mobilprogramlamauyg.appspot.com',
    iosClientId: '890687616159-eqb0nsskb9lhs5nk13o1gpjmq5s0h7vu.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobilprogramlamauyg',
  );
}
